# Generated by Django 4.2.11 on 2024-03-27 21:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0002_post_tag_delete_about_delete_client_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='tags',
            field=models.ManyToManyField(to='homepage.tag'),
        ),
    ]
